### PR TITLE
Fix getChangeMap logic for year filter

### LINKED ISSUE #22: Logic for filtering change map by year is wrong
In the `getChangeMap` function, the LandTrendr results image array is first subset to the segment that is either hi/lo limit case for start year, magnitude, or duration. Later, the selected segments are filtered by year, duration, etc.

**Problem**: in this flow the selected segment might be e.g. outside of the year range filter when someone wants to know what is the greatest disturbance between 2010 and 2020. There could have been a disturbance that occurred in that year range, but if it is not the greatest in the time series, no results will be returned.

**Proposed solution**: apply all of the filters to the segments array first and do the segment selection by first/last, least/greatest, fastest/slowest last.

**Breaking changes**: I don't think this will break anything. Results before and after the change could be different. Would argue that the results from the proposed change is what people are expecting but not getting right now and are unaware.

### PR DESCRIPTION
**Pull request by jdbcode**
Closes #22 

Changes the order of filtering and change identity selection. The current code identifies change segment first and then filters it. This flow order can result in missed change when the year filter is used and change identified as greatest/least, earliest/latest, fastest/slowest etc. The fix is to filter the segments first and then select by change identity.

### CODE REVIEW

**Comment by jdbcode** [comment]
I've done some testing to ensure that the changes WAI, but if you are aware of specific cases where the old implementation was incorrect, please test them. You can use the script mentioned [here](https://github.com/eMapR/LT-GEE/issues/22#issuecomment-889650331) for testing - change parameters as needed (see [docs](https://emapr.github.io/LT-GEE/api.html#getchangemap) for parameter defs).

File: LandTrendr.js [hunk 1]
```diff
@@ -1502,117 +1502,108 @@ exports.getChangeMap = function(lt, changeParams){
...
-      sortByThis = changeParams.segInfo.arraySlice(0,0,1);
-      break;
-    case 'fastest':
-      sortByThis = changeParams.segInfo.arraySlice(0,5,6);
-      break;
-    case 'slowest':
-      sortByThis = changeParams.segInfo.arraySlice(0,5,6).multiply(-1); // need to flip the delta here, since arraySort is working by ascending order
-      break;
-  }
+  var segInfo = ltgee.getSegmentData(lt, changeParams.index, changeParams.delta);
```
Comment (ramblingrek) [inline LandTrendr.js]: I'm confused why we would be calling ltgee here --isn't that this file?  Why do we need the ltgee prefix?

Comment (jdbcode) [reply LandTrendr.js]: Good catch, thanks!
Yes, `ltgee` should not be called, this was left in by mistake when I transferred the changes into this file from an external development file.
I've removed it.

File: LandTrendr.js [hunk 2]
```diff
@@ -1502,117 +1502,108 @@ exports.getChangeMap = function(lt, changeParams){
...
-                             distArray.arraySlice(0,5,6).arrayProject([1]).arrayFlatten([['dur']]),
-                             distArray.arraySlice(0,2,3).arrayProject([1]).arrayFlatten([['preval']]),
-                             distArray.arraySlice(0,6,7).arrayProject([1]).arrayFlatten([['rate']]),
-                             distArray.arraySlice(0,7,null).arrayProject([1]).arrayFlatten([['dsnr']]));
-                             //distArray.arraySlice(0,3,4).arrayProject([1]).arrayFlatten([['verts']])); /// added by peter 2/27/2020
-  
-  // start a mask based on magnitudes greater than 0 to get rid of the masked pixels from the orginal collection
-  var mask = distImg.select('mag').gt(0);
-  mask = ee.Image(1).mask(mask);
+  var changeMask = segInfo.arraySlice(0, 4, 5).gt(0);
```
Comment (ramblingrek) [inline LandTrendr.js:1507]: Is this filtering on magnitude?   I may not be tracking, but does this limit us to only disturbance?  Or does this get flipped beforehand depending on whether we're looking at disturbance vs growth?

Comment (jdbcode) [reply LandTrendr.js:1507]: Yes, that's a filter on magnitude (the delta of the segments in units of the input image band used for segmentation).

The `segInfo` array is the result of a call to `getSegmentData` which returns either

- all segments
- gain only segments (veg growth/recovery)
- loss only segments (veg loss)

...depending on a passed argument.

The magnitude of loss or gain is always absolute value, read as ____ units lost (disturbance) or ____ units gained (recovery). This is true for all measures of magnitude (raw abs delta, rate, DSNR).

In the context of the `getChangeMap` function (the function in review), a user requests either loss or gain as the target segments using the `changeParams.delta` parameter, then a series of filters are applied to the selected segments. `var changeMask = segInfo.arraySlice(0, 4, 5).gt(0);` (your comment line) is creating a mask for the pixels of interest; at this point `segInfo` is an array of valid segments (segments of interest; either gain or loss only) and invalid segments; valid segments have actual information for all attributes, invalid segments have -9999 for all attributes. When we `.gt(0)` we are identifying all of the valid segments and will mask the invalid segments out.

**Comment by jdbcode** [comment]
Robert, if you are satisfied with the changes, please approve your review and merge.

**Review by ramblingrek — APPROVED** [review]

**Comment by jdbcode** [comment]
🎉😃

**Comment by jdbcode** [comment]
Change synced to git-on-borg: https://earthengine.googlesource.com/users/emaprlab/public/+/42cceae74ff928d6909aee0a8b02f095a47da8a7/Modules/LandTrendr.js
